### ISSUE TITLE
Week 7 suggestions 

### ISSUE THREAD

**Issue by sigu** [CraftAcademy/ca_course#101]
1. gem rails12factor no longer needed in rails5 apps as advised by [official heroku rails12factor repo](https://github.com/heroku/rails_12factor#new-rails-5-apps)

2 . Having the exact version of the javascript npm packages can save the hustle of version incompatibility. The notorious victim in this being `ng-resource` which when installed without a version defaults to version 1.6.3 which requires angular1.6.3 otherwise the angular gods sends us to stackoverflow while ionic 1 had and depends on angular1.5.3

``` bash
$ bower i angular-resource@1.5.3 --save
```
3. The error related to cors and how to solve it is not necessary in step 5 as it has been set up correctly in the rails api setup. The other option is to not set it up initialy so the students can experience the error first and understand ytf they are including that section ( i actually prefer this last option :smiley: )

![screenshot from 2017-03-21 09-36-11](https://cloud.githubusercontent.com/assets/584211/24148408/b5d568ac-0e4f-11e7-8d82-834a06326966.png)

### performance data factory

![screenshot from 2017-03-21 16-09-38](https://cloud.githubusercontent.com/assets/584211/24148673/e17eca4c-0e50-11e7-842d-e73b5eacb92d.png)

4. Typo of the word `performance` in the factories. This occurs more than once in step 5 of the cooper challenge

5. The backend url is currently pointing to `/api/v1/data` while as we had set up rails previously the path should actually be `/api/v1/performance_data` or consider changing the routes on the rails backend 

6. Setting up the performance_data factory we have just a default config for `query` throws an error too as it expects the result to be an array but we are actually returning a json which is an object from the backend.
We can however make `query` to accept an object instead of the default array by adjusting our config as shown below
``` javascript
  .factory('performanceData', function ($resource, API_URL) {
    return $resource(API_URL + '/performance_data',
                     {},
                     {query:  {method:'GET', isArray:false}}
                    );
  });
```
This is seen in the [angular docs on $resource ](https://docs.angularjs.org/api/ngResource/service/$resource)

**Comment by diraulo** [comment]
>1. gem rails12factor no longer needed in rails5 apps as advised by official heroku rails12factor repo

Now that I think about it, we never needed it in the first place... This was an API only app

> 3. The error related to cors and how to solve it is not necessary in step 5 as it has been set up correctly in the rails api setup. The other option is to not set it up initialy so the students can experience the error first and understand ytf they are including that section ( i actually prefer this last option 😃 )

This is actually not a CORS issue but I believe at the time we couldn't make request to the server because some headers were not exposed with request and so we want them to add those at that step. Note that there are lines that are not present in the CORS setup ... Also maybe something changed and this is no longer an issue 🤔

**Comment by diraulo** [comment]
Number 6, has actually been fixed in the book but wasn't updated on edX
