### ISSUE TITLE
Add instructions for setting up QT

### ISSUE THREAD

**Issue by tochman** [CraftAcademy/ca_course#105]
We would probably benefit from using Capybara Webkit rather than Poltergaist for testing java script. For that, the learners need to have QT installed on their localhost. 

https://github.com/thoughtbot/capybara-webkit

**Comment by sigu** [comment]
I cant assign myself to this - lack of permissions @tochman assign me

**Comment by sigu** [comment]
We might also consider the option of moving to the new headless chrome instead of using this option. I will provide instructions for this though

**Comment by sigu** [comment]
# Linux (Ubuntu and other debian based distros)
Required before doing the installation
- Ruby installed in the system

1. Update your system to get the latest packages

```bash
 sudo apt-get update -y
 ```
 2. Install necessary build tools for compilation of packages

 ```bash
 sudo apt-get install build-essential -y
 ```

 3. The capybara-webkit gem needs the Qt toolchain (including qmake and the webkit library and header files). You want version 4.8 or later but not higher than qt5.5.1

```bash
 sudo apt-get install libqtwebkit-dev -y
 ```
 4. install the gem

```bash
 gem install capybara-webkit
```

# MacOs

We will use homebrew in this process. Have it installed in your system

- Install Qt via homebrew. First update the formulas, then try installing the built binary with:

```bash
  brew update
  brew install qt
```

**Option:** If that doesn't work, try building it from source (which can take more than an hour):

```bash
  brew install qt --build-from-source
```

- install the gem
```bash
 gem install capybara-webkit
```

**Comment by diraulo** [comment]
Perhaps we should just refer the students to this link? https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit

It is regularly kept up-to-date with instructions on how to install `Qt` for virtually all the operating systems our student will make use of. For now, @sigu consult that doc and update your instructions accordingly if needed for the OSes we're using.

**Comment by sigu** [comment]
@diraulo It is the link that I used, the wiki has too much noise for a beginner but in case they face problems trying to follow my instructions or have other OSes they can refer to that link
