### ISSUE TITLE
Create screencasts for week 5

### ISSUE THREAD

**Issue by diraulo** [CraftAcademy/ca_course#123]
We need screencasts on the following topics. Add more if I missed something.
- [ ] Rails routing
- [ ] Active Record basics
- [ ] Rails Helpers
- [ ] Nested Routes (I have a recording of this, will check it out) - Might need to make a short one though.. 🤔

**Comment by diraulo** [comment]
My idea is to have most of the concepts outlined [here](http://guides.rubyonrails.org/)

We have recordings on those concepts (with no tests, just focusing on the basics). The example can still be the article project, we can use that to present all those concepts. The aim is to release these videos in advance, students watch them over the weekend and on Monday we introduce the same project but this time with the AUT Cycle. 

We can have further discussions during the week with students on the various topics they need clarifications on

**Comment by faraznaeem** [comment]
Not relevant any more
