### ISSUE TITLE
Unclear code examples on javascript modules

### ISSUE THREAD

**Issue by sigu** [CraftAcademy/ca_course#126]
On the aliasing sections, the code examples and explanation on what aliasing is is vague and needs update

**Comment by diraulo** [comment]
Any link to the content you're referring to? @sigu

**Comment by sigu** [comment]
This content right here https://github.com/CraftAcademy/ca_course/blob/master/javascript-modules.md#importing-the-exported-values

**Comment by faraznaeem** [comment]
Whole section is overhauled
