### ISSUE TITLE
Update week 2 content to ES6

### ISSUE THREAD

**Issue by diraulo** [CraftAcademy/ca_course#127]
Week 2 should start to introduce ES6.

We now have `classes` available with that and could really work well with trying to compare with a true OOP language like Ruby.

We can also introduce them to other concepts like
- Arrow functions
- String interpolation
- Iterators (`forEach`, `map`, etc...)
- And more of the ES6+ goodies

**Comment by diraulo** [comment]
Maybe consider #54 as well.

**Comment by faraznaeem** [comment]
Done
