### ISSUE TITLE
Fix path for report download

### ISSUE THREAD

**Issue by tochman** [CraftAcademy/ca_course#37]
if you go to http://class.craftacademy.se/courses/course-v1:CraftAcademy+CA-101+2016-1/instructor#view-data_download and click the link to the generated report.
] 
it is

``` file:///tmp/edx-s3/grades/course-v1%253ACraftAcademy%252BCA-101%252B2016-1/CraftAcademy_CA-101_2016-1_student_profile_info_2016-04-19-1825.csv
```

So, that is definitely a problem. :wink:

**Comment by diraulo** [comment]
In order to solve this issue with need to connect the app to an S3 storage  bucket.

**Comment by diraulo** [comment]
This issue was solved with the last deployment I made so closing it.
