### ISSUE TITLE
Create a policy for updates of OpenEdx

### ISSUE THREAD

**Issue by tochman** [CraftAcademy/ca_course#38]
The edx-platform is being continuously developed. We need to make a decision if and how often we will pull in the latest changes to out deploy. 

```
https://github.com/edx/edx-platform/commits/master
```

**Comment by diraulo** [comment]
With the resources we have at the moment, as long as the system is stable let's not worry too much about constant updates on the main repo. We can have monthly reviews of changes from upstream and decide whether or not they're critical for us to have on our instance.​

**Comment by diraulo** [comment]
Follow openedX Release cycle and deploy stable name versions listed [here](https://openedx.atlassian.net/wiki/spaces/DOC/pages/11108700/Open+edX+Releases)
