### ISSUE TITLE
The arithmetic operators chapter in prep course needs correction

### ISSUE THREAD

**Issue by rdcsg** [CraftAcademy/ca_course#49]
http://class.craftacademy.se/courses/course-v1:CraftAcademy+CA-101+20016-3/courseware/740f18738dc644c1b114c190effa5cc7/c289c6ce14b64944b747e7da61ee2db0/?activate_block_id=block-v1%3ACraftAcademy%2BCA-101%2B20016-3%2Btype%40sequential%2Bblock%40c289c6ce14b64944b747e7da61ee2db0&child=first

Has some errors, simple stuff and I still understand what you mean - but nevertheless.
For instance 10-20 = 10 is not correct.
and the equals at the end of the page are the same but they should be different.

**Comment by diraulo** [comment]
- [ ] update gitbook
- [ ] update edx

**Comment by diraulo** [comment]
Updated [this version](http://studio.craftacademy.se/course/course-v1:CraftAcademy+CA-101+20016-3) of the edX course. We should clone this one in future
