### ISSUE TITLE
Week 2 - BMI Challenge > Wrap up > Moving on

### ISSUE THREAD

**Issue by lollypop27** [CraftAcademy/ca_course#56]
Point 3: "like ZURB **Foundationhttp://foundation.zurb.com/or**" change to "like ZURB Foundation http://foundation.zurb.com/ or"

update link when clicked it takes you to a craft academy document page

- [ ] check and update gitbook
- [ ] update edX

**Comment by diraulo** [comment]
@joaonzangoII same as #57 -- check if it's correct in the book. If not fix it there and let me know I'll update on edX
