### ISSUE TITLE
Week 2 - BMI Challenge > Wrap up > Moving on

### ISSUE THREAD

**Issue by lollypop27** [CraftAcademy/ca_course#57]
Point 3: "like ZURB **Foundationhttp://foundation.zurb.com/or**" change to "like ZURB Foundation http://foundation.zurb.com/ or"

update link,  when clicked it takes you to a craft academy document page, link to http://foundation.zurb.com

- [ ] check and update gitbook
- [ ] update edX

**Comment by diraulo** [comment]
@joaonzangoII Check if this link is well formatted in the gitbook

**Comment by diraulo** [comment]
same as #56
