### ISSUE TITLE
installing NodeJs on Ubuntu

### ISSUE THREAD

**Issue by lollypop27** [CraftAcademy/ca_course#58]
There needs to be instructions on installing Nodejs on Ubuntu, course notes only for mac.

found this: http://www.hostingadvice.com/how-to/install-nodejs-ubuntu-14-04/#node-version-manager

use option 2 and worked 100% installing the LTS version

Option 2: Install Node.js with Ubuntu Package Manager

To install Node.js, type the following command in your terminal:
$sudo apt-get install nodejs

Then install the Node package manager, npm:
$sudo apt-get install npm

Create a symbolic link for node, as many Node.js tools use this name to execute.
$sudo ln -s /usr/bin/nodejs /usr/bin/node

Now we should have both the Node and npm commands working:
$ node -v
shows version being used
$ npm -v
shows version being used

**Comment by diraulo** [comment]
Thanks @lollypop27 I will be revisiting the Linux instructions this week and update them, especially now that we have more and more Linux users.

**Comment by lollypop27** [comment]
Fantastic!

**Comment by diraulo** [comment]
This issue will be resolved as part of #59
