### ISSUE TITLE
Update Linux Install instructions

### ISSUE THREAD

**Issue by diraulo** [CraftAcademy/ca_course#59]
The current instructions are possibly out-dated. We need to go through them on the fresh install of Ubuntu 14.04 (or perhaps upgrade to 16.04) and make sure that everything works as expected.

**Comment by joaonzangoII** [comment]
@diraulo  I have tested the current instructions we have on the Coding as a Craft Bootcamp prep gitbook and all seems well with regards to dependencies with Ubuntu 16.04 so we can upgrade the ubuntu version we ask the students to install on their machines!

**Comment by diraulo** [comment]
Thanks @joaonzangoII. I just invited you to our gitbook organization. You should be able to access the book and edit them. 

I would create a new branch from the gitbook editor and submit a PR when you're done editing for review. Perhaps we should look into this together. Last time I tried this it didn't work as expected.

As for the content update, we need the following:
- [ ] Upgrade [instructions](https://craftacademy.gitbooks.io/caa_precourse/content/terminal/linux.html) to support to 16.06
- [ ] Add a section about setting up `zsh` with [Pretzo](https://github.com/sorin-ionescu/prezto).
- [ ] Add instructions on how to configure shell theme after installing Pretzo. Recommended theme: `giddie` or `steeef`

**Comment by diraulo** [comment]
@joaonzangoII you can get the gitbook editor for linux [here](https://www.gitbook.com/editor/linux)

**Comment by joaonzangoII** [comment]
@diraulo 16.06?

**Comment by diraulo** [comment]
@joaonzangoII was a typo i fixed it 😉

**Comment by diraulo** [comment]
@joaonzangoII How are we looking on this?

**Comment by joaonzangoII** [comment]
@diraulo I have pushed changes to a new branch on pre_course

**Comment by diraulo** [comment]
thanks for this @joaonzangoII
