### ISSUE TITLE
Setup a new instance of open edX

### ISSUE THREAD

**Issue by diraulo** [CraftAcademy/ca_course#60]
- [x] Deploy & Configure a new instance of edX
- [x] Connects to S3 for storage
- [x] Create a DB server on AWS and link the app to it
- [ ] ~~Enable Insights - #36~~
- [x] Migrate existing data to new database
- [ ] ~~Add support for Certificates - #35~~
- [x] Setup log/bug tracker (Airbrake or Sentry) - #42
- [x] Document every steps of the process

**Comment by tochman** [comment]
Any progress on this @diraulo ?

**Comment by diraulo** [comment]
Done 🚀
