### ISSUE TITLE
Youtube-channel - Wrong brand

### ISSUE THREAD

**Issue by Marcus-CA** [CraftAcademy/ca_course#64]
Our youtube-channel: https://www.youtube.com/channel/UCJifjJ-LgbQfTLUvear2gfw 

We using the brand "Makers Academy" on our youtube-channel.

**Comment by tochman** [comment]
![skarmavbild 2016-07-19 kl 11 18 35](https://cloud.githubusercontent.com/assets/5248170/16946004/cf85f00a-4da7-11e6-8ddb-20f294ad2f20.png)

**Comment by diraulo** [comment]
@tochman Let me know how to access the channel and I can take care of this today.

**Comment by diraulo** [comment]
This issue has now been resolved.
