### ISSUE TITLE
Instructions to install RubyMine [Linux]

### ISSUE THREAD

**Issue by diraulo** [CraftAcademy/ca_course#67]
Add steps to install Rubymine to the Linux setup guide.

**Comment by joaonzangoII** [comment]
@diraulo  I am on it

**Comment by diraulo** [comment]
@sigu can you take this story over?

**Comment by diraulo** [comment]
@sigu ?? 🤔

**Comment by diraulo** [comment]
closing this... and recommend we use [VS Code](https://code.visualstudio.com/)
