### ISSUE TITLE
Comparisons & Manipulations

### ISSUE THREAD

**Issue by AmberWilkie** [CraftAcademy/ca_course#71]
typeof(3) == typeof(3.4) == typeof(0x34) == "number"
does not evaluate to true.

**Comment by diraulo** [comment]
@AmberWilkie @tochman reason this is wrong is because:

- it first evaluate `typeof(3) == typeof(3.4)` which returns `true` 
- then it does `true == typeof(0x34)` which obviously is `false` because ( `true != "number"`)

**Comment by diraulo** [comment]
Closing this.. the corresponding section was updated in the course material.
