### ISSUE TITLE
Have jQuery intro in pre-course?

### ISSUE THREAD

**Issue by diraulo** [CraftAcademy/ca_course#73]

**Comment by joaonzangoII** [comment]
@diraulo  what do you have in mind?

**Comment by diraulo** [comment]
I'm not sure ... I was just thinking we need to have this covered in the precourse. Have them practice it at least at some stage because in the first weeks of the course they make use of it and what I picked up is that they only discover it within their first JS challenge.

We could have a write up on the topic or choose a resource online and reference it in the material and have additional exercises to practice it. Basic stuff like selecting elements on a page, triggering events, etc...

@tochman any thoughts on this? @joaonzangoII if you want to explore this that'd be good. I'm open to suggestions

**Comment by tochman** [comment]
Good idea. Perhaps we can have a JS + jQuery section?

**Comment by AmberWilkie** [comment]
I've moved the Javascript introduction to the prep course and have included a short reference for where to pick up some jQuery. It needs to be expanded a bit so we explain why they are learning jQuery and perhaps some of the most common commands or places to start playing around.
