### ISSUE TITLE
The Gitbook and edX materials for Week 5 are wildly different

### ISSUE THREAD

**Issue by AmberWilkie** [CraftAcademy/ca_course#91]
Gitbook has tons of text and implementing a messaging app with mailbox gem. The course materials are using articles. Wtf?

**Comment by diraulo** [comment]
@AmberWilkie The 'Legacy Code' student gets at week 5 comes from those instructions you see there. The whole point of this exercise is to give them an undocumented project and have them figure out what's going on with the code and in the process write tests for all existing code before adding new functionalities to it. So giving them step-by-step instructions on how the app is actually built would defeat the purpose of this project.

Maybe @tochman will have more to say about that...

**Comment by AmberWilkie** [comment]
Yeah I feel you but edX and gitbook are just totally different. So it's an issue because theoretically edX should be a copy of gitbook. Not that I have been able to make any changes in gitbook branches for some time.
