### ISSUE TITLE
Change width of side menu

### ISSUE THREAD

**Issue by rmzse** [CraftAcademy/ca_course#92]
I want to be able to change whether the side menu is expanded or not, either on my command or on small screens for which it should turn into a thin sidebar and not occupy the entire width like it does today.

Background:
This is how i work: I push the browser window to the left so i can maximise course mtrl and coding window
![image](https://cloud.githubusercontent.com/assets/13518870/21108158/766ded6e-c094-11e6-88be-02e675bdd921.png)

It works when only dealing with edX but it's not great when accessing other important info
![image](https://cloud.githubusercontent.com/assets/13518870/21108179/91624ffc-c094-11e6-83c5-2477e072ad4f.png)

**Comment by diraulo** [comment]
edX recently updated the design of this menu, so this issue will likely be resolved as soon as I deploy the latest version.
