### ISSUE TITLE
VirtualBox on Windows Setup

### ISSUE THREAD

**Issue by lollypop27** [CraftAcademy/ca_course#95]
@diraulo the Virtualbox link that you have on the course material, rather use this one https://www.virtualbox.org/wiki/Downloads.

Course Notes: http://class.craftacademy.se/courses/course-v1:CraftAcademy+CA-101+2016-3/courseware/740862fe88d346f78213c8ade4df5050/a24842a71d5c49bca908802e9d60d5da/

The one you have points to an old version and does not work on Windows 10

**Comment by faraznaeem** [comment]
Done
