### ISSUE TITLE
Prep course Ruby typos?

### ISSUE THREAD

**Issue by ceca2017** [CraftAcademy/ca_course#98]
Ruby prep course:

I found some things that to me at least looks  like it could be some typos? See what you think:

The Basics => Arrays => Pop and Push
“The pop method has and alias called the shovel operator”
Should be 
“The push method …”

Classes => The initialise method
“Try this code in irb by defining the class and trying to instantiate an new Account object. “
Should be ?
“… new House object.”

Methods
Class dog:  
attr_accessor :breed, name
name should be :name ?

**Comment by diraulo** [comment]
Fixed
